 Sorular :

 # https://github.com/EmincanY


1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.
2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.
5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.
6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.
7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.
8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.
9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.
10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.
11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.
12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin
16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [2]:
# Q-1 
# 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini 
# (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

import numpy as np
array_1 = np.arange(30)
print("Array_1 1 Demensional: \n",array_1)
array_1 = array_1.reshape(15,2)
print("Array_1 2 Demensional: \n",array_1)

Array_1 1 Demensional: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Array_1 2 Demensional: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]


In [3]:
# Q-2
# 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve 
# son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

array_2 = np.random.randint(0,100,60)
print("Array_2 1 Demensional: \n",array_2)
array_2 = array_2.reshape(3,4,-1)
print("Array_2 3 Demensional: \n",array_2)

Array_2 1 Demensional: 
 [85 53 84 62 65 77 23 27  7 55 40 15  1 67 59 88 65 84 17  9  3 92 87 42
 61 62 62 96 69 62 37 94 38 89 95 42 33 61 39 34  4 79 27 10 22 21 30 70
 10 64 64 46 52 32 32 26 47 77 43 60]
Array_2 3 Demensional: 
 [[[85 53 84 62 65]
  [77 23 27  7 55]
  [40 15  1 67 59]
  [88 65 84 17  9]]

 [[ 3 92 87 42 61]
  [62 62 96 69 62]
  [37 94 38 89 95]
  [42 33 61 39 34]]

 [[ 4 79 27 10 22]
  [21 30 70 10 64]
  [64 46 52 32 32]
  [26 47 77 43 60]]]


In [4]:
# Q-3
# 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. 
# Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

array_2d = np.random.randint(0,10,(4,5))
print("Array_2d 2 Demensional: \n",array_2d)
array_2d_to_1d = array_2d.reshape(-1)
print("Array_2d 1 Demensional: \n",array_2d_to_1d)

Array_2d 2 Demensional: 
 [[1 7 3 4 3]
 [3 1 3 5 8]
 [7 4 6 3 8]
 [1 3 4 7 6]]
Array_2d 1 Demensional: 
 [1 7 3 4 3 3 1 3 5 8 7 4 6 3 8 1 3 4 7 6]


In [11]:
# Q-4
# İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. 
# Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.

array_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("\n For Loop: \n")
for i in range(array_2d.shape[0]):
    for j in range(array_2d.shape[1]):
        print(array_2d[i,j])

print("\n NumPy Method: \n")
for i in np.nditer(array_2d):
    print(i)




 For Loop: 

1
2
3
4
5
6
7
8
9
10

 NumPy Method: 

1
2
3
4
5
6
7
8
9
10


In [12]:
# Q-5
# 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
# 1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
# Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.
array_1 = np.array([5,10,15,20,25,30])
array_2 = np.array([1,2,3,4,5,6])
print("\n Addition: \n",array_1 + array_2)
print("\n Subtraction: \n",array_1 - array_2)
print("\n Multiplication: \n",array_1 * array_2)
print("\n Division: \n",array_1 / array_2)



 Addition: 
 [ 6 12 18 24 30 36]

 Subtraction: 
 [ 4  8 12 16 20 24]

 Multiplication: 
 [  5  20  45  80 125 180]

 Division: 
 [5. 5. 5. 5. 5. 5.]


In [13]:
# Q-6
# 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.

array_3 = np.random.randint(0,100,10)
print("\n Array_3: \n",array_3)
print("\n Sum: \n",array_3.sum())
print("\n Mean: \n",array_3.mean())
print("\n Max: \n",array_3.max())
print("\n Var: \n",array_3.var())
print("\n Std: \n",array_3.std())



 Array_3: 
 [24 47 62 22 11 22 94 95 88 75]

 Sum: 
 540

 Mean: 
 54.0

 Max: 
 95

 Var: 
 978.8

 Std: 
 31.285779517218362


In [15]:
# Q-7
# 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. 
# Ardından bu iki array'i concatenate ederek ekrana yazdırın.
array_1 = np.arange(0,21)
array_2 = np.arange(500,531)
print("Array_1: \n",array_1)
print("Array_2: \n",array_2)
print("Concatenate: \n",np.concatenate([array_1,array_2]))



Array_1: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Array_2: 
 [500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517
 518 519 520 521 522 523 524 525 526 527 528 529 530]
Concatenate: 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514
 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530]


In [16]:
# Q-8
# 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. 
# Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. 
# Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.

array_1 = np.arange(15,51, dtype = int)
array_2 = np.arange(10,101, dtype = int)
concatanate_array = np.concatenate([array_1,array_2])
concatanate_array[25:51] = 888
print("Concatanate Array: \n",concatanate_array)

Concatanate Array: 
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39 888 888 888 888 888 888 888 888 888 888 888
 888 888 888 888 888 888 888 888 888 888 888 888 888 888 888  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [22]:
# Q-9
# 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  
# 320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. 
# Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.

array_1 = np.arange(0,40).reshape(8,5)
array_2 = np.arange(320,360).reshape(8,5)

axis_0 = np.concatenate([array_1,array_2],axis = 0)
axis_1 = np.concatenate([array_1,array_2],axis = 1)

print("Axis_0: \n",axis_0)
print("Axis_1: \n",axis_1)



Axis_0: 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]
Axis_1: 
 [[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]


In [25]:
# Q-10
# 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.

array_1 = np.arange(0,40).reshape(4,2,5)
array_2 = np.arange(320,360).reshape(4,2,5)

axis_2 = np.concatenate([array_1,array_2], axis = 2)
axis_2_stack = np.stack([array_1,array_2], axis = 2)

print("Axis_2: \n",axis_2)
print("Axis_2_Stack: \n",axis_2_stack)


Axis_2: 
 [[[  0   1   2   3   4 320 321 322 323 324]
  [  5   6   7   8   9 325 326 327 328 329]]

 [[ 10  11  12  13  14 330 331 332 333 334]
  [ 15  16  17  18  19 335 336 337 338 339]]

 [[ 20  21  22  23  24 340 341 342 343 344]
  [ 25  26  27  28  29 345 346 347 348 349]]

 [[ 30  31  32  33  34 350 351 352 353 354]
  [ 35  36  37  38  39 355 356 357 358 359]]]
Axis_2_Stack: 
 [[[[  0   1   2   3   4]
   [320 321 322 323 324]]

  [[  5   6   7   8   9]
   [325 326 327 328 329]]]


 [[[ 10  11  12  13  14]
   [330 331 332 333 334]]

  [[ 15  16  17  18  19]
   [335 336 337 338 339]]]


 [[[ 20  21  22  23  24]
   [340 341 342 343 344]]

  [[ 25  26  27  28  29]
   [345 346 347 348 349]]]


 [[[ 30  31  32  33  34]
   [350 351 352 353 354]]

  [[ 35  36  37  38  39]
   [355 356 357 358 359]]]]


In [26]:
# Q-11
# [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. 
# Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

array_1 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
print("Index of 5: \n",np.where(array_1 == 5))


Index of 5: 
 (array([ 5, 13], dtype=int64),)


In [27]:
# Q-12 
# Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
array_1 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
print("Index of Even Numbers: \n",np.where(array_1 % 2 == 0))

Index of Even Numbers: 
 (array([ 1,  3,  4,  6,  7,  9, 11], dtype=int64),)


In [28]:
# Q-13
# Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
array_1 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
print("Index of Numbers Greater Than 4: \n",np.where(array_1 > 4))


Index of Numbers Greater Than 4: 
 (array([ 1,  2,  5,  9, 10, 11, 13], dtype=int64),)


In [29]:
# Q-14
# Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
array_1 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
print("Index of Numbers Divisible by 5: \n",np.where(array_1 % 5 == 0))


Index of Numbers Divisible by 5: 
 (array([ 1,  2,  5, 13], dtype=int64),)


In [32]:
# Q-15
# 85-100(100 dahil) arasından rastgele 1 tam sayı seçin

print("Random Number: \n",np.random.randint(85,101))

Random Number: 
 97


In [33]:
# Q-16
# İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
array_1 = np.random.randint(10,100,(3,3))
print("Random Array: \n",array_1)

Random Array: 
 [[25 63 89]
 [23 47 79]
 [62 45 34]]


In [34]:
# Q-17
# 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
array_1 = np.arange(35,61)
print("Random Choice: \n",np.random.choice(array_1))

Random Choice: 
 49


In [35]:
# Q-18
# Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.
array_1 = np.array([[3, 8, 10, 53],[3, 8, 10, 53]])
print("Array: \n",array_1)


Array: 
 [[ 3  8 10 53]
 [ 3  8 10 53]]
